### ISSUE TITLE
KeyError: '23'

### ISSUE THREAD

**Issue by zyywmy** [bioinform/somaticseq#26]
Hi, 
I just tried to run SomaticSeq.Wrapper.sh for a Dream dataset. I got an error as followings. Could you let me know what the reason?
"Traceback (most recent call last):
  File "/home/wangm6/resource/somaticseq-2.2.2/SSeq_merged.vcf2tsv.py", line 434, in <module>
    if args.cosmic_vcf:        got_cosmic,  cosmic_variants,  cosmic_line  = genome.find_vcf_at_coordinate(my_coordinate, cosmic_line,  cosmic,  chrom_seq)
  File "/mnt/nfs/gigantor/ifs/DCEG/Home/wangm6/resource/somaticseq-2.2.2/genomic_file_handlers.py", line 617, in find_vcf_at_coordinate
    latest_vcf_run  = catchup_multilines(my_coordinate, latest_vcf_line, vcf_file_handle, chrom_seq)
  File "/mnt/nfs/gigantor/ifs/DCEG/Home/wangm6/resource/somaticseq-2.2.2/genomic_file_handlers.py", line 574, in catchup_multilines
    is_behind = whoisbehind( coordinate_i, coordinate_j, chrom_sequence )
  File "/mnt/nfs/gigantor/ifs/DCEG/Home/wangm6/resource/somaticseq-2.2.2/genomic_file_handlers.py", line 378, in whoisbehind
    chrom1_position = chrom_sequence[chrom1]
KeyError: '23'"

**Comment by zyywmy** [comment]
I saw 23 and 24 in the cosmic b37_cosmic_v54_120711.vcf. Is this reason for causing the error?

**Comment by ltfang-bina** [comment]
Yes, that is the reason. 
I guess you can manually change 23 and 24 into X or Y (or chrX and chrY), depends on the contig name used in the reference fasta file.
