### ISSUE TITLE
update somaticseq on anaconda

### ISSUE THREAD

**Issue by fpbarthel** [bioinform/somaticseq#64]
Hi,

Is it possible to update somaticseq on anaconda? current version there is 2.8.1

https://anaconda.org/bioconda/somaticseq

Thanks!

**Comment by ltfang-bina** [comment]
How do I do that? I didn't originally put somaticseq on anaconda.

**Comment by fpbarthel** [comment]
Oh hm I don't know actually! I am also not sure who to contact. Do you strongly recommend 3.+ vs using 2.8.1?

**Comment by ltfang-bina** [comment]
I'll try to find out how to update anaconda. 
Version 3 is refactored to make it more modular and easier to add features, etc., but in terms of current function it's identical to version 2.8.1 (so far).

**Comment by fpbarthel** [comment]
Thank you!

**Comment by guoyuh** [comment]
hi:
    I installde the software somaticseq by annoconda  and firstly run as follow ,but it takes some errors ,  could you tell me why it happened ?,thanks 

`somaticseq_parallel.py \
> --output-directory $OUTPUT_DIR \
> --genome-reference $ref \
> --inclusion-region $BED \
> single \
> --bam-file tumor.bam \
> --mutect2-vcf MuTect2/variants.vcf \
> --varscan-vcf VarScan2/variants.vcf \
> --vardict-vcf VarDict/variants.vcf \
> --lofreq-vcf LoFreq/variants.vcf \
> --scalpel-vcf Scalpel/variants.indel.vcf \
> --strelka-vcf Strelka/variants.vcf
2019-09-30 13:43:25,716 - SomaticSeq - INFO - SomaticSeq Input Arguments: output_directory=/home/vip/somaticseq/out, genome_reference=/data/bigbiosoft/GATK/resources/bundle/hg19/ucsc.hg19.fasta, truth_snv=None, truth_indel=None, classifier_snv=None, classifier_indel=None, pass_threshold=0.5, lowqual_threshold=0.1, homozygous_threshold=0.85, heterozygous_threshold=0.01, minimum_mapping_quality=1, minimum_base_quality=5, minimum_num_callers=0.5, dbsnp_vcf=None, cosmic_vcf=None, inclusion_region=/home/vip/lxdata/bed/lung9_gene_format.bed, exclusion_region=None, threads=1, keep_intermediates=False, somaticseq_train=False, bam_file=tumor.bam, sample_name=TUMOR, mutect_vcf=None, mutect2_vcf=MuTect2/variants.vcf, varscan_vcf=VarScan2/variants.vcf, vardict_vcf=VarDict/variants.vcf, lofreq_vcf=LoFreq/variants.vcf, scalpel_vcf=Scalpel/variants.indel.vcf, strelka_vcf=Strelka/variants.vcf, which=single
sh: 1: cannot create MuTect2/variants0fc31c543cc0455d925b9d2e24909c21.vcf: Directory nonexistent
Error: Unable to open file MuTect2/variants.vcf. Exiting.
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/vip/miniconda3/envs/somaticseq/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/home/vip/miniconda3/envs/somaticseq/lib/python3.6/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/home/vip/miniconda3/envs/somaticseq/bin/somaticseq_parallel.py", line 43, in runSingle_by_region
    run_somaticseq.runSingle(outdir_i, ref, bam, sample_name, truth_snv, truth_indel, classifier_snv, classifier_indel, pass_threshold, lowqual_threshold, hom_threshold, het_threshold, dbsnp, cosmic, inclusion, exclusion, mutect, mutect2, varscan, vardict, lofreq, scalpel, strelka, min_mq, min_bq, min_caller, somaticseq_train, ensembleOutPrefix, consensusOutPrefix, classifiedOutPrefix, keep_intermediates)
  File "/home/vip/miniconda3/envs/somaticseq/lib/python3.6/site-packages/somaticseq/run_somaticseq.py", line 155, in runSingle
    outSnv, outIndel, intermediateVcfs, tempFiles = combineCallers.combineSingle(outdir=outdir, ref=ref, bam=bam, inclusion=inclusion, exclusion=exclusion, mutect=mutect, mutect2=mutect2, varscan=varscan, vardict=vardict, lofreq=lofreq, scalpel=scalpel, strelka=strelka, keep_intermediates=True)
  File "/home/vip/miniconda3/envs/somaticseq/lib/python3.6/site-packages/somaticseq/combine_callers.py", line 49, in combineSingle
    mutect2_in = bed_intersector(mutect2, os.sep.join(( outdir, 'intersect.mutect2.vcf' )), inclusion, exclusion)
  File "/home/vip/miniconda3/envs/somaticseq/lib/python3.6/site-packages/vcfModifier/vcfIntersector.py", line 60, in bed_intersector
    assert exit_code == 0
AssertionError
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/vip/miniconda3/envs/somaticseq/bin/somaticseq_parallel.py", line 144, in <module>
    subdirs = pool.map(runSingle_by_region_i, bed_splitted)
  File "/home/vip/miniconda3/envs/somaticseq/lib/python3.6/multiprocessing/pool.py", line 266, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/home/vip/miniconda3/envs/somaticseq/lib/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
AssertionError
`

**Comment by ltfang-bina** [comment]
Just wondering, did you actually run MuTect2 to create the MuTect2/variants.vcf file?
You did have `\` after each line to break up the one command into multiple lines, right?

**Comment by guoyuh** [comment]
Thank you for your reply
I didn't create MuTect2 / variants.vcf with Mutect2, I mean somaticseq is to help me create MuTect2 / variants.vcf with MuTect2；
I did have \ after each line to break up the one command into multiple lines
commond   as  follow ：
`somaticseq_parallel.py \
--output-directory  $OUTPUT_DIR \
--genome-reference  $ref \
--inclusion-region  $BED \
--algorithm         ada \
paired \
--tumor-bam-file    /home/vip/project/somatic/NPC10F-T/02_bamdst/NPC10F-T.sorted.algn.bam \
--normal-bam-file   /home/vip/project/somatic/NPC10F-N/02_bamdst/NPC10F-N.sorted.bqsr.bam \
--mutect2-vcf       MuTect2/variants.vcf \
--varscan-snv       VarScan2/variants.snp.vcf \
--varscan-indel     VarScan2/variants.indel.vcf \
--jsm-vcf           JointSNVMix2/variants.snp.vcf \
--somaticsniper-vcf SomaticSniper/variants.snp.vcf \
--vardict-vcf       VarDict/variants.vcf \
--muse-vcf          MuSE/variants.snp.vcf \
--lofreq-snv        LoFreq/variants.snp.vcf \
--lofreq-indel      LoFreq/variants.indel.vcf \
--scalpel-vcf       Scalpel/variants.indel.vcf \
--strelka-snv       Strelka/variants.snv.vcf \
--strelka-indel     Strelka/variants.indel.vcf`

**Comment by ltfang-bina** [comment]
`somaticseq_parallel.py` is to combine caller's results, so all the `--mutect2-vcf`, `--varscan-vcf`, etc. are inputs to the program. 
I'm not too sure what's in the conda package. SomaticSeq's repo does have a semi-automatic wrapper script that runs those tools with dockers: `https://github.com/bioinform/somaticseq/tree/master/utilities/dockered_pipelines`. But SomaticSeq at its core is just a method to combine/consolidate individual callers' results.

**Comment by ltfang-bina** [comment]
Looked into conda installation, `makeSomaticScripts.py` is a way to create some dockerized somatic mutation calling scripts (`makeSomaticScripts.py single -h`). 
Conda also installed a bunch of callers like gatk, varscan2, etc..... those are not exactly part of SomaticSeq. You need to run them first before running SomaticSeq.

**Comment by ltfang-bina** [comment]
...... someone has packaged latest somaticseq on conda: https://anaconda.org/bioconda/somaticseq

**Comment by ltfang-bina** [comment]
...... someone has packaged latest somaticseq on conda: https://anaconda.org/bioconda/somaticseq
