### ISSUE TITLE
Exception: LoFreq.snvs.concat.vcf.gz does not seem to be properly sorted

### ISSUE THREAD

**Issue by t-neumann** [bioinform/somaticseq#66]
Hi,

I got the following error when running SomaticSeq train with the following command:

```
singularity exec /groups/zuber/zubarchive/USERS/tobias/.singularity/somaticseq:3.0.0.img \
/opt/somaticseq/somaticseq/run_somaticseq.py \
--somaticseq-train \
--output-directory /groups/obenauf/NGS_data/GIAB/tumor-normal/somaticSeq/train/model \
--genome-reference /groups/obenauf/Software/hg38/Homo_sapiens_assembly38.fasta \
--inclusion-region /groups/obenauf/NGS_data/GIAB/tumor-normal/benchmark/truth/na12878-na24385-somatic-hg38-truth-regions.bed \
 \
 \
--dbsnp /groups/zuber/zubarchive/USERS/tobias/hg38/GATK/Homo_sapiens_assembly38.dbsnp138.vcf \
 \
 \
--truth-snv /groups/obenauf/NGS_data/GIAB/tumor-normal/somaticSeq/train/truth/na12878-na24385-somatic-hg38-truth.snp.recode.vcf.gz \
--truth-indel /groups/obenauf/NGS_data/GIAB/tumor-normal/somaticSeq/train/truth/na12878-na24385-somatic-hg38-truth.indel.recode.vcf.gz \
 \
paired \
--tumor-bam-file /groups/obenauf/NGS_data/GIAB/tumor-normal/aln/NA12878_NA24385_mixture.aligned.sorted.dedup.bam \
--normal-bam-file  /groups/obenauf/NGS_data/GIAB/tumor-normal/aln/NA24385_normal.aligned.sorted.dedup.bam \
 \
 \
--mutect2-vcf /groups/obenauf/NGS_data/GIAB/tumor-normal/somaticSeq/train/trainingInput/MuTect2.concat.vcf \
 \
 \
 \
--somaticsniper-vcf /groups/obenauf/NGS_data/GIAB/tumor-normal/somaticSeq/train/trainingInput/SomaticSniper.concat.vcf \
--vardict-vcf /groups/obenauf/NGS_data/GIAB/tumor-normal/somaticSeq/train/trainingInput/VarDict.concat.vcf \
 \
--lofreq-snv /groups/obenauf/NGS_data/GIAB/tumor-normal/somaticSeq/train/trainingInput/LoFreq.snvs.concat.vcf.gz \
--lofreq-indel /groups/obenauf/NGS_data/GIAB/tumor-normal/somaticSeq/train/trainingInput/LoFreq.indels.concat.vcf.gz \
--scalpel-vcf /groups/obenauf/NGS_data/GIAB/tumor-normal/somaticSeq/train/trainingInput/Scalpel.concat.vcf \
--strelka-snv /groups/obenauf/NGS_data/GIAB/tumor-normal/somaticSeq/train/trainingInput/Strelka.snvs.concat.vcf.gz \
--strelka-indel /groups/obenauf/NGS_data/GIAB/tumor-normal/somaticSeq/train/trainingInput/Strelka.indels.concat.vcf.gz > sseq_train.log 2> sseq_train.err
```

This is the error.

```
2018-11-04 09:49:27,786 - SomaticSeq - INFO - SomaticSeq Input Arguments: output_directory=/groups/obenauf/NGS_data/GIAB/tumor-normal/somaticSeq/train/model, genome_reference=/groups/obenauf/Software/hg38/Homo_sapiens_assembly38.fasta, truth_snv=/groups/obenauf/NGS_data/GIAB/tumor-normal/somaticSeq/train/truth/na12878-na24385-somatic-hg38-truth.snp.recode.vcf.gz, truth_indel=/groups/obenauf/NGS_data/GIAB/tumor-normal/somaticSeq/train/truth/na12878-na24385-somatic-hg38-truth.indel.recode.vcf.gz, classifier_snv=None, classifier_indel=None, pass_threshold=0.5, lowqual_threshold=0.1, homozygous_threshold=0.85, heterozygous_threshold=0.01, minimum_mapping_quality=1, minimum_base_quality=5, minimum_num_callers=0.5, dbsnp_vcf=/groups/zuber/zubarchive/USERS/tobias/hg38/GATK/Homo_sapiens_assembly38.dbsnp138.vcf, cosmic_vcf=None, inclusion_region=/groups/obenauf/NGS_data/GIAB/tumor-normal/benchmark/truth/na12878-na24385-somatic-hg38-truth-regions.bed, exclusion_region=None, threads=1, keep_intermediates=False, somaticseq_train=True, tumor_bam_file=/groups/obenauf/NGS_data/GIAB/tumor-normal/aln/NA12878_NA24385_mixture.aligned.sorted.dedup.bam, normal_bam_file=/groups/obenauf/NGS_data/GIAB/tumor-normal/aln/NA24385_normal.aligned.sorted.dedup.bam, tumor_sample=TUMOR, normal_sample=NORMAL, mutect_vcf=None, indelocator_vcf=None, mutect2_vcf=/groups/obenauf/NGS_data/GIAB/tumor-normal/somaticSeq/train/trainingInput/MuTect2.concat.vcf, varscan_snv=None, varscan_indel=None, jsm_vcf=None, somaticsniper_vcf=/groups/obenauf/NGS_data/GIAB/tumor-normal/somaticSeq/train/trainingInput/SomaticSniper.concat.vcf, vardict_vcf=/groups/obenauf/NGS_data/GIAB/tumor-normal/somaticSeq/train/trainingInput/VarDict.concat.vcf, muse_vcf=None, lofreq_snv=/groups/obenauf/NGS_data/GIAB/tumor-normal/somaticSeq/train/trainingInput/LoFreq.snvs.concat.vcf.gz, lofreq_indel=/groups/obenauf/NGS_data/GIAB/tumor-normal/somaticSeq/train/trainingInput/LoFreq.indels.concat.vcf.gz, scalpel_vcf=/groups/obenauf/NGS_data/GIAB/tumor-normal/somaticSeq/train/trainingInput/Scalpel.concat.vcf, strelka_snv=/groups/obenauf/NGS_data/GIAB/tumor-normal/somaticSeq/train/trainingInput/Strelka.snvs.concat.vcf.gz, strelka_indel=/groups/obenauf/NGS_data/GIAB/tumor-normal/somaticSeq/train/trainingInput/Strelka.indels.concat.vcf.gz, tnscope_vcf=None, which=paired
2018-11-04 09:53:55,647 - somatic_vcf2tsv.py - INFO - NO RE-SCALING
/usr/local/lib/python3.6/dist-packages/scipy/stats/stats.py:4971: RuntimeWarning: invalid value encountered in double_scalars
  z = (s - expected) / np.sqrt(n1*n2*(n1+n2+1)/12.0)
Traceback (most recent call last):
  File "/opt/somaticseq/somaticseq/run_somaticseq.py", line 357, in <module>
    keep_intermediates = runParameters['keep_intermediates'] )
  File "/opt/somaticseq/somaticseq/run_somaticseq.py", line 71, in runPaired
    somatic_vcf2tsv.vcf2tsv(is_vcf=outSnv, nbam_fn=nbam, tbam_fn=tbam, truth=truth_snv, cosmic=cosmic, dbsnp=dbsnp, mutect=mutect_infile, varscan=varscan_snv, jsm=jsm, sniper=sniper, vardict=intermediateVcfs['VarDict']['snv'], muse=muse, lofreq=lofreq_snv, scalpel=None, strelka=strelka_snv, tnscope=intermediateVcfs['TNscope']['snv'], dedup=True, min_mq=min_mq, min_bq=min_bq, min_caller=min_caller, ref_fa=ref, p_scale=None, outfile=ensembleSnv)
  File "/opt/somaticseq/somaticseq/../somaticseq/somatic_vcf2tsv.py", line 400, in vcf2tsv
    if lofreq:  got_lofreq,  lofreq_variants,  lofreq_line  = genome.find_vcf_at_coordinate(my_coordinate, lofreq_line,  lofreq,  chrom_seq)
  File "/opt/somaticseq/somaticseq/../genomicFileHandler/genomic_file_handlers.py", line 563, in find_vcf_at_coordinate
    latest_vcf_run  = catchup_multilines(my_coordinate, latest_vcf_line, vcf_file_handle, chrom_seq)
  File "/opt/somaticseq/somaticseq/../genomicFileHandler/genomic_file_handlers.py", line 514, in catchup_multilines
    raise Exception('{} does not seem to be properly sorted'.format(filehandle_j.name) )
Exception: /groups/obenauf/NGS_data/GIAB/tumor-normal/somaticSeq/train/trainingInput/LoFreq.snvs.concat.vcf.gz does not seem to be properly sorted
```

I checked and there are variants in the ```LoFreq.snvs.concat.vcf.gz``` vcf file and it appears to be sorted otherwise indexing with tabix would not work right?

Any ideas?

**Comment by ltfang-bina** [comment]
Try making sure it's sorted in the same order as the reference fasta you've used. That exception is thrown when the VCF file is sorted differently from the reference file.

**Comment by t-neumann** [comment]
Thanks @ltfang-bina that resolved it.
